export const LOGOUT = 'LOGOUT'

export const SIGN_IN_USER_REQUEST = 'SIGN_IN_USER_REQUEST'
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS'
export const SIGN_IN_USER_FAILURE = 'SIGN_IN_USER_FAILURE'

export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST'
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS'
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE'

export const DELETE_USER_ADDRESS_REQUEST = 'DELETE_USER_ADDRESS_REQUEST'
export const DELETE_USER_ADDRESS_SUCCESS = 'DELETE_USER_ADDRESS_SUCCESS'
export const DELETE_USER_ADDRESS_FAILURE = 'DELETE_USER_ADDRESS_FAILURE'

export const RETRIEVE_USER_PROFILE_REQUEST = 'RETRIEVE_USER_PROFILE_REQUEST'
export const RETRIEVE_USER_PROFILE_SUCCESS = 'RETRIEVE_USER_PROFILE_SUCCESS'
export const RETRIEVE_USER_PROFILE_FAILURE = 'RETRIEVE_USER_PROFILE_FAILURE'

export const ADD_RESTAURANT_TO_FAVORITES_REQUEST = 'ADD_RESTAURANT_TO_FAVORITES_REQUEST'
export const ADD_RESTAURANT_TO_FAVORITES_SUCCESS = 'ADD_RESTAURANT_TO_FAVORITES_SUCCESS'
export const ADD_RESTAURANT_TO_FAVORITES_FAILURE = 'ADD_RESTAURANT_TO_FAVORITES_FAILURE'
