export const CLEAR_CART_REQUEST = 'CLEAR_CART_REQUEST'
export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS'
export const CLEAR_CART_FAILURE = 'CLEAR_CART_FAILURE'

export const UPDATE_CART_ITEM_REQUEST = 'UPDATE_CART_ITEM_REQUEST'
export const UPDATE_CART_ITEM_SUCCESS = 'UPDATE_CART_ITEM_SUCCESS'
export const UPDATE_CART_ITEM_FAILURE = 'UPDATE_CART_ITEM_FAILURE'

export const ADD_MENU_ITEM_TO_CART_REQUEST = 'ADD_MENU_ITEM_TO_CART_REQUEST'
export const ADD_MENU_ITEM_TO_CART_SUCCESS = 'ADD_MENU_ITEM_TO_CART_SUCCESS'
export const ADD_MENU_ITEM_TO_CART_FAILURE = 'ADD_MENU_ITEM_TO_CART_FAILURE'

export const RETRIEVE_CART_BY_USER_ID_REQUEST = 'RETRIEVE_CART_BY_USER_ID_REQUEST'
export const RETRIEVE_CART_BY_USER_ID_SUCCESS = 'RETRIEVE_CART_BY_USER_ID_SUCCESS'
export const RETRIEVE_CART_BY_USER_ID_FAILURE = 'RETRIEVE_CART_BY_USER_ID_FAILURE'

export const DELETE_CART_ITEM_FROM_CART_REQUEST = 'DELETE_CART_ITEM_FROM_CART_REQUEST'
export const DELETE_CART_ITEM_FROM_CART_SUCCESS = 'DELETE_CART_ITEM_FROM_CART_SUCCESS'
export const DELETE_CART_ITEM_FROM_CART_FAILURE = 'DELETE_CART_ITEM_FROM_CART_FAILURE'
