export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const DELETE_USER_NOTIFICATIONS = 'DELETE_USER_NOTIFICATIONS'

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST'
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS'
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE'

export const RETRIEVE_USER_ORDERS_REQUEST = 'RETRIEVE_USER_ORDERS_REQUEST'
export const RETRIEVE_USER_ORDERS_SUCCESS = 'RETRIEVE_USER_ORDERS_SUCCESS'
export const RETRIEVE_USER_ORDERS_FAILURE = 'RETRIEVE_USER_ORDERS_FAILURE'

export const RETRIEVE_RESTAURANT_ORDERS_REQUEST = 'RETRIEVE_RESTAURANT_ORDERS_REQUEST'
export const RETRIEVE_RESTAURANT_ORDERS_SUCCESS = 'RETRIEVE_RESTAURANT_ORDERS_SUCCESS'
export const RETRIEVE_RESTAURANT_ORDERS_FAILURE = 'RETRIEVE_RESTAURANT_ORDERS_FAILURE'

export const RETRIEVE_USER_NOTIFICATIONS_REQUEST = 'RETRIEVE_USER_NOTIFICATIONS_REQUEST'
export const RETRIEVE_USER_NOTIFICATIONS_SUCCESS = 'RETRIEVE_USER_NOTIFICATIONS_SUCCESS'
export const RETRIEVE_USER_NOTIFICATIONS_FAILURE = 'RETRIEVE_USER_NOTIFICATIONS_FAILURE'
